# Generated by Django 4.2.4 on 2023-09-15 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mwonimoney', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={},
        ),
    ]
