spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 875956331523-t41sdqqi1uj1esl3u222kogktvtjfmjb.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://j9b310.p.ssafy.io/api/login/oauth2/code/google
            scope:
              - email
          kakao:
            client-id: ee79d6a7c99b90866eeba9a9bc103236
            client-secret: U9zWosrIKvEZzaX6ovJLDvESgPe5adO2
            scope:
              - profile_nickname
              - account_email
              - birthday
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: http://j9b310.p.ssafy.io/api/login/oauth2/code/kakao
            client-authentication-method: client_secret_post

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

app:
  oauth2:
    authorizedRedirectUris: http://localhost:3000/oauth/redirect

jwt:
  key: mwonimoneymwonimoneymwonimoneymwonimoneymwonimoneymwonimoneymwonimoneymwonimoneymwonimoney