spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ee79d6a7c99b90866eeba9a9bc103236
            client-secret: U9zWosrIKvEZzaX6ovJLDvESgPe5adO2
            scope:
              - profile_nickname
              - account_email
              - birthday
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/api/login/oauth2/code/kakao
            client-authentication-method: client_secret_post

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

data:
  redis:
    host: j9b310.p.ssafy.io
    port: 6379

datasource:
  driver-class-name: org.mariadb.jdbc.Driver
  url: jdbc:mariadb://j9b310.p.ssafy.io:50000/wannabedb
  username: wannabe
  password: i9b310p_kplyjc

jpa:
  hibernate:
    ddl-auto: create
  show-sql: true

logging:
  level:
    org:
      hibernate: info

app:
  oauth2:
    authorizedRedirectUris: http://localhost:3000/oauth/redirect

jwt:
  key: ascdfjkavfabdjkcbasdjkajkqwcwasd
