spring:
  data:
    couchbase:
      bucket-name: mwonimoney
cloud:
  aws:
    stack:
      auto: false
    region:
      static: ap-northeast-2
    credentials:
      secret-key: temp
      access-key: temp