spring:
  profiles:
    include: JPA,MariaDB,MongoDB,Oauth,Redis,Swagger,S3
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
logging:
  level:
    org.springframework.security: debug







